// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostalService;

namespace PostalService.Migrations
{
    [DbContext(typeof(PostBase))]
    [Migration("20220504142833_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("PostalService.MemoryStreamAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullFileNameOnDisk")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostMessagesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostMessagesId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("PostalService.PostMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderString")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PostMessages");
                });

            modelBuilder.Entity("PostalService.MemoryStreamAttachment", b =>
                {
                    b.HasOne("PostalService.PostMessage", null)
                        .WithMany("AttachmentFiles")
                        .HasForeignKey("PostMessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
